name: MLOps Credit Score CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Linting with flake8
      run: |
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Unit Tests (Pytest)
      env:
        ENV=development
        API_SECRET_KEY=troque_por_uma_chave_forte_aqui
        VALID_PARTNERS=user:password
        TOKEN_EXPIRE_MIN=60
        MLFLOW_TRACKING_URI=sqlite:///mlruns.db
        EXPERIMENT_NAME=QuantumFinance_Credit_Score_Alternativo
        MODEL_NAME=XGBoost_Transaction_Score
        MIN_ROC_AUC=0.75
        DATA_RAW_URL=https://storage.googleapis.com/ds-publico/IA/BaseDefault01.csv
        API_URL=http://localhost:8000
      run: |
        pytest tests/
        
    - name: Validar Feature Store (Feast Plan)
      run: |
        cd feature_repo
        feast plan